apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: client_go_role_binding
subjects:
  - kind: ServiceAccount
    name: default # Name is case sensitive
    namespace: default
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: client_go_role # must match the name of the Role
  apiGroup: rbac.authorization.k8s.io
